### PR TITLE
fix(logger): don't log timestamps when outputting json

### PR DESCRIPTION
**Pull request by ewanharris**
Currently if `--output json` is requested then a timestamp is output which breaks parsing the JSON output. So disable the timestamps if we're in json mode.

### CODE REVIEW

**Comment by m1ga** [comment]
For me `ti info --output json` doesn't show a timestamp but when I run `ti info --timestamp --output json` I still get a timestamp even with this PR. It looks like `--output json` is not setting `this.json` to true.

**Comment by ewanharris** [comment]
@m1ga my bad, I forgot to include that the user on tislack had the config setting set. I'll go back and check on the info output, I'd only really tested on the SDK command.

**Comment by ewanharris** [comment]
Alrighty, take two at this. I've done the same as other methods that explicitly call a function when set. Although I'm not sure on the source of the failing tests...

**Comment by m1ga** [comment]
thats lookig better!
`ti info --output json --timestamp` only outputs the json now!

tested:
* `ti sdk --output json --timestamp`
* `ti config --output json --timestamp`
* `ti info --output json --timestamp`
* `ti plugin --output json --timestamp`
* `ti module --output json --timestamp`

without `--timestamp` and without `--output json`.

All looked as expected.

**Review by m1ga — APPROVED** [review]
:+1:

**Pull request closed without merging**
